[google_credentials]
type = "service_account"
project_id = "neurophet-hr"
private_key_id = "your-private-key-id"
private_key = "your-private-key"
client_email = "your-client-email"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-client-x509-cert-url"

[google_sheets]
department_job_sheet_id = "1SfVtvaHgXesDFtdFozt9CJD8aQpPBrK76AxNj-OOfFE"
interview_evaluation_sheet_id = "1SfVtvaHgXesDFtdFozt9CJD8aQpPBrK76AxNj-OOfFE"
evaluation_template_sheet_id = "1SfVtvaHgXesDFtdFozt9CJD8aQpPBrK76AxNj-OOfFE"

[OPENAI_API_KEY]
key = "your-openai-api-key"